name: Rotate Product Configuration

on:
  workflow_dispatch:  
  push:
    branches:
      - main
    tags:
      # SemVer 2.0.0 compliant patterns
      # Core: MAJOR.MINOR.PATCH (e.g., 1.0.0)
      # Optional: -PRERELEASE (e.g., -alpha.1)
      # Optional: +BUILD (e.g., +exp.sha.5114f85)
      
      # Pattern without v prefix
      - '[0-9]+.[0-9]+.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?'
      
      # Pattern with v prefix (common convention)
      - 'v[0-9]+.[0-9]+.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?'

jobs:
  rotate-config:
    name: Rotate product config
    permissions:
      actions: write
    
    secrets:
      token: ${{ secrets.ROTATOR_TOKEN }}
    
    uses: thetechcollective/gh-rotator/.github/workflows/dispatch.yml@experimental
    
    with:
      product-repo: config-rotator/product-sample
      product-workflow: .github/workflows/rotator.yml
