name: Rotate Product Configuration

on:
  workflow_dispatch:  
  push:
    branches:
      - main
    tags:
      # This pattern matches tags like 1.2.3
      - '[0-9]+.[0-9]+.[0-9]+*'  # e.g. 1.2.3, 1.2.3-rc, etc.

jobs:
  rotate-config:
    name: Rotate product config
    permissions:
      actions: write
    
    uses: thetechcollective/gh-rotator/.github/workflows/rotate-config.yml@experimental
    
    with:
      product-repo: config-rotator/product-sample
      product-workflow: .github/workflows/rotator.yml
      token: ${{ ${{ secrets.ROTATOR_TOKEN }}  
      rotator-pin: experimental
